name: CI
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      # install & configure python
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # install & configure poetry
      - name: Install Poetry
        uses: snok/install-poetry@v1

      # install your root project, if required
      - name: Install dependencies
        run: poetry install --no-interaction

      # run test suite
      - name: Lint
        run: make lint

      - name: mypy
        run: make mypy

      - name: Tests
        run: make test
